# Generated by Django 5.0.4 on 2024-04-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterList',
            fields=[
                ('parameterId', models.AutoField(primary_key=True, serialize=False)),
                ('parameterName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartDetails',
            fields=[
                ('partId', models.AutoField(primary_key=True, serialize=False)),
                ('partName', models.CharField(max_length=255)),
                ('partCost', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('partReputation', models.IntegerField(default=5)),
                ('partLead', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='PartInputParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.partdetails')),
                ('partInputParameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.parameterlist')),
            ],
        ),
        migrations.CreateModel(
            name='PartOutputParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.partdetails')),
                ('partOutputParameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.parameterlist')),
            ],
        ),
    ]
