# Generated by Django 5.0.4 on 2024-05-30 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_functionlist_partgoalfunctions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterVersionHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childParameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='tool.parameterlist')),
                ('parentParameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tool.parameterlist')),
            ],
        ),
    ]
